- README.md
- demo_templates/webhook.yaml
- handle_actions.go
- model.go
Adding the feature of sending webhooks.
Example of the yaml:
```
- key: webhooks
expect:
http:
method: GET
path: /send_webhook_to_httpbin
actions:
- send_http:
url: "https://httpbin.org/post"
method: POST
body: '{"hello": "world"}'
headers:
X-Token: t123
- reply_http:
status_code: 200
body: 'webhooks sent'
```
> Add send_http action

- amqp.go
- docker-compose.yml
- redis.go
Any network or server-side connection failures will stop the amqp's worker. This pr adds reconnection to fix the issue.
> Fix amqp reconnection

- demo_templates/http.yaml
Tested with curl.
```
curl -v -XPOST localhost:9999/soap_example
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9999 (#0)
> POST /soap_example HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/xml; charset = utf-8
< Date: Thu, 16 May 2019 21:46:00 GMT
< Content-Length: 399
<
* Connection #0 to host localhost left intact
<?xml version = "1.0"?> <SOAP-ENV:Envelope    xmlns:SOAP-ENV = "http://www.w3.org/2001/12/soap-envelope"    SOAP-ENV:encodingStyle = "http://www.w3.org/2001/12/soap-encoding">     <SOAP-ENV:Body xmlns:m = "http://www.xyz.org/quotation">       <m:GetQuotationResponse>          <m:Quotation>Here is the quotation</m:Quotation>       </m:GetQuotationResponse>    </SOAP-ENV:Body> …
```
> Add soap example

- template.go
- template_test.go
This pr extracts the template instance to be global so that templates can reference each other. We are going to leverage `{{define ...}}{{end}}` syntax from https://golang.org/pkg/text/template/#hdr-Nested_template_definitions.
The idea of components will be similar to the "predefined templates reused in other templates" test. We can render the components first (will be implemented in the next PRs) and then use `{{template ...}}` to reuse the components.
> Prepare for components

- demo_templates/http.yaml
- load.go
- load_test.go
- model.go
- model_test.go
- openmock.go
- template_test.go
- Add Kind in the YAML block
- Add very basic `Validate` function for the YAML blocks
- Define `Template` with `kind: Template` and `template: ...`
Tested locally.
```
curl localhost:9999/get_with_template
{ "foo": "bar", "name": "my_template_1", "http_path": "/get_with_template" } 
```
> Add template reuse and kinds

- demo_templates/http.yaml
- demo_templates/webhook.yaml
Tested locally. Sent a webhook to https://user1:password1@httpbin.org/basic-auth/user1/password1
```
$ make build
$ USER=user1 PASSWORD=password1 make run
[http] 2019/08/21 11:26:57 HTTP Request: GET /basic-auth/user1/password1 HTTP/1.1          
Host: httpbin.org                                                                          
[http] 2019/08/21 11:26:57 HTTP Response: HTTP/1.1 200 OK                                 
Connection: close
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json
Date: Wed, 21 Aug 2019 18:27:00 GMT
Referrer-Policy: no-referrer-when-downgrade
Server: nginx
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
{
"authenticated": true,
"user": "user1"
}
```
> Add basicauth example

- .circleci/config.yml
- .golangci.yml
- Makefile
- admin.go
- amqp.go
- cmd/om/main.go
- handle_actions.go
- handle_actions_test.go
- kafka.go
- load.go
- openmock.go
- redis.go
- redis_test.go
- template_helper.go
- template_helper_test.go
Fixing all the linter issues
e.g.
```
handle_actions_test.go:24: File is not `gofmt`-ed with `-s` (gofmt)                                                            
Actions: []ActionDispatcher{ActionDispatcher{}},                                                       
openmock.go:12:15: struct of size 248 bytes could be of size 224 bytes (maligned)                                              
type OpenMock struct {                                                             
^                                                                                                                
handle_actions_test.go:51:25: Error return value of `unActingMock.DoActions` is not checked (errcheck)               
unActingMock.DoActions(Context{})                    
^ …
```
> Add linter

- demo_templates/http.yaml
One can test it with
```
curl -v "localhost:9999/long_conditions?foo1=bar1&foo2=bar2&foo3=bar3"
```
> Add long conditions example

- README.md
- demo_templates/complicated_values.yml
- demo_templates/ordered_actions.yml
- load.go
- load_test.go
- model.go
- when extending an AbstractBehavior, run all of the actions defined for both the abstract behavior and the concrete behavior
- to allow customization when needed in extending, add an 'order' field to determine the order the actions are run
> Merge actions when extending AbstractBehavior

- openmock.go
Sometimes we saw things like:
```
time="2019-12-04T22:08:21Z" level=info msg="template with key:verifications loaded."
time="2019-12-04T22:08:21Z" level=fatal msg="cannot setup watcher: too many open files"
```
If the openmock setup doesn't need hot reload (e.g. in a stable environment), we can disable this feature.
> Add hot reload env var

- demo_templates/webhook_example.yaml
- handle_actions.go
- model.go
- model_test.go
See https://github.com/checkr/openmock/pull/55 for a write-up of the behavior we're trying to fix.  This change makes it so a `reply_http` action will flush the connection, sending the response to the requesting client, and then move on to running other actions defined by the `Behavior`.  
Also add validation to make sure that only one request_http is included per behavior (otherwise the connection would have been flushed when you try to run the second), and add a test for that validation.   Added an example in `demo_templates/webhook_example.yaml` of how to implement this kind of delayed webhook response.
> Flush the HTTP response connection when doing reply_http action

- admin.go
- admin_test.go
- go.mod
- go.sum
- load.go
- load_test.go
- redis.go
- redis_test.go
Current
Openmock has an admin interface (HTTP on port 9998 by default) that allows user to POST new templates. Pseudo code: 
Unmarshal POST body as YAML into an open mock model (400 if fails) 
Foreach mock in loaded model
S = marshal mock to YAML
Redis hset redis_templates_storage <mock key> S
End
Restart OM process
When the OM (re)starts, it loads up YAML strings from the templates directory files, and from the redis key redis_templates_storage, and concatenates them into one big YAML string, which it then unmarshals into an OM model.  The redis stuff is loaded with `redis HGETALL redis_templates_storage`
The other functionality to note is that, when evaluating go templates in om (e.g. in conditions, http_reply bodies, etc), the `redisDo` commands lets mock users run arbitrary redis …
> Implement post-key for manipulating the OM model via the HTTP admin interface

- load.go
- before this change, templating will fail if there is not a new line
charater at end of each yml file
> loadYAML always adds a new line

- cmd/omctl/cmd/delete.go
- cmd/omctl/cmd/root.go
- cmd/omctl/cmd/update.go
- load.go
Add ability to interact with remote openmock instance's template_sets endpoint to omctl. 
* add `-k` param to let user specify set_key for commands
* adjust `push` command to hit `template_sets/:set_key` if `-k` is specified
* add `delete` command specifically working with `-k` to delete templates that were earlier pushed
Manual test plan: 
* spun up a local om `OPENMOCK_REDIS_TYPE=redis OPENMOCK_REDIS_URL=redis://localhost:6379 OPENMOCK_TEMPLATES_DIR=~/Documents/misc/templates ./om`
* posted demo templates at it `./omctl push -d demo_templates/ -k frank`
* GET http://localhost:9998/api/v1/templates to verify frank templates were posted 
* deleted demo templates `./omctl delete -k frank`
* GET http://localhost:9998/api/v1/templates again, verify frank templates no longer present
No unit …
> Add template sets interactions to omctl CLI

- load.go
- load_test.go
Currently if you want to perform `send_http` events with arbitrary data from a file (vs a kafka,ampq, or http payload) there is no way to do so since we do not do not replace the `ActionSendHTTP` `Body` field with the data in the file path located in the `BodyFromFile` field. We already do this for all other models with a `BodyFromFile` field.
Tested locally, looks good 👍 
test template looks like:
```
- key: ping
kind: Behavior
expect:
http:
method: GET
path: /ping
actions:
- reply_http:
status_code: 200
body: OK
headers:
Content-Type: text/xml
- sleep:
duration: 10s
- send_http:
url: http://localhost:9999/hello
method: POST
body_from_file: ../files/test.tpl
- key: hello
kind: Behavior
expect:
http:
method: POST
path: /hello
actions:
- reply_http:
status_code: 200
body: '{{ .HTTPBody }}' …
```
> Load body_from_file for ActionSendHTTP

- README.md
the cli om was removed, and we moved to swagger server so no need to use the old `om` cli.
> Update readme and remove om usage

- README.md
- demo_templates/abstract_behaviors.yml
Add an `AbstractBehavior` example to address https://github.com/checkr/openmock/issues/70.
> Add AbstractBehavior example value-with-numbers

- .circleci/config.yml
- .golangci.yml
- Dockerfile
- Makefile
- demo_templates/http.yaml
- handle_actions.go
Previously the headers in `reply_http` and `send_http` are not rendered with the context, this PR adds that so that headers can also be dynamic.
Example:
```
- key: base64-basicauth-with-env
kind: Behavior
expect:
http:
method: POST
path: /base64-basicauth-with-env
actions:
- reply_http:
headers:
Authorization: '{{ printf "foobar:%s" (env "BASIC_AUTH_PASS") | b64enc }}'
status_code: 200
```
> Add headers rendering and example of basicauth

- README.md
- docker-compose.yml
- kafka.go
- openmock.go
- Update docker-compose to use an updated version of kafka
- Update kafka consumer logic so that when an error happened it `Fatal` the process instead of just log the error. This helps to avoid the app failed silently (though with some error message)
- Added `kt` as one of the containers inside the docker-compose, so that we have a reliable way to test mocks inside the docker-compose network. This is because interacting with `kt` at the docker host (i.e. localhost:9092) is not usually working.
> Improve the experience of running kafka locally

- handle_actions.go
- http.go
- openmock.go
- Fixed .HTTPPath. It was set as `ec.Path()` which doesn't render path params. For example, path `/report/:id` will be literal in echo's Path() function. We should render the path with its actual runtime value
- Reduce the logging noise by removing `logrus.SetReportCaller(true)`
- Adding `SetDebug(true)` for send_http actions
> Fix http path context and fix logging noise
